# Generated by Django 3.2 on 2022-05-31 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tvseries', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='serie',
            options={'verbose_name': 'TV Series'},
        ),
        migrations.AlterUniqueTogether(
            name='episode',
            unique_together={('episode_number', 'season')},
        ),
        migrations.AlterUniqueTogether(
            name='season',
            unique_together={('serie', 'season_number')},
        ),
    ]
