# Generated by Django 3.2 on 2022-05-31 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tvseries', '0002_auto_20220531_1635'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='serie',
            options={'verbose_name': 'TV Serie', 'verbose_name_plural': 'Tv Series'},
        ),
    ]
