# Generated by Django 3.2 on 2022-05-31 23:29

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tvseries', '0008_alter_serie_options'),
        ('ratingapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='rating',
            unique_together={('user', 'episode')},
        ),
    ]
