# Generated by Django 3.2 on 2022-06-01 01:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ratingapp', '0002_alter_rating_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='rating',
            unique_together=set(),
        ),
    ]
